export const NAME_MIN_CHARS = 1;
export const NAME_MAX_CHARS = 30;
export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 30;
export const PASSWORD_MIN_CHARS = 8;
export const PASSWORD_MAX_CHARS = 30;
export const PHONE_DIGITS = 10;
export const PHONE_REGEX = /^\d{10}$/;
export const STREET_MIN_CHARS = 1;
export const STREET_MAX_CHARS = 40;
export const STREET_REGEX = /^[a-zA-Z0-9 .]{1,40}$/;
export const COUNTRY_MIN_CHARS = 1;
export const COUNTRY_MAX_CHARS = 30;
export const COUNTRY_REGEX = /^[a-zA-Z ]{1,30}$/;
export const CITY_MIN_CHARS = 1;
export const CITY_MAX_CHARS = 30;
export const CITY_REGEX = /^[a-zA-Z ]{1,30}$/;
export const EMAIL_REGEX = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
export const DIGIT_REGEX = /\d/;
export const LETTER_REGEX = /[a-zA-Z]/;
export const ALPHA_NUMERIC_REGEX = /^[a-zA-Z0-9]+$/;
export const SPECIAL_CHARS_REGEX = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/;
export const DEFAULT_IMAGE = 'https://tse1.mm.bing.net/th?q=blank%20profile%20picture%20image';
export const MAX_YEAR_SPAN = 3;
export const DEFAULT_EVENT_IMAGE = 'https://leekduck.com/assets/img/events/events-default.jpg';
export const SAVE_CATEGORY_ICON = 'https://img.icons8.com/ios/100/40C057/ok--v1.png';
export const CANCEL_CATEGORY_ICON = 'https://img.icons8.com/color/96/cancel--v1.png';
/* User images */
export const TODOR_SAVOV_IMAGE = 'https://firebasestorage.googleapis.com/v0/b/expense-tracking-app-33495.appspot.com/o/users%2FIMG_0597.jpeg?alt=media&token=c0f116a5-bfa0-4a56-baeb-142247a94045';
export const EXPENSE_NAME_MIN_CHARS = 1;
export const EXPENSE_NAME_MAX_CHARS = 25;
export const AMOUNT_MIN_CHARS = 1;
export const AMOUNT_MAX_CHARS = 10;
export const ALPHA_NUMERIC_SPACE_REGEX = /^[a-zA-Z0-9\s]+$/;
export const ALPHA_SPACE_REGEX = /^[a-zA-Z\s]+$/;
export const LETTERS_ONLY_REGEX = /^[a-zA-Z]+$/;
export const CATEGORY_NAME_MIN_LENGTH = 3;
export const CATEGORY_NAME_MAX_LENGTH = 20;